/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6gui;

/**
 *
 * @author ASUS
 */
public class Konversi extends javax.swing.JFrame {

    /**
     * Creates new form Konversi
     */
    public Konversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MasukkanBil = new javax.swing.JTextField();
        BtnBiner = new javax.swing.JButton();
        BtnDesimal = new javax.swing.JButton();
        HasilBiner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HasilDesimal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Konversi Bilangan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 130, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Masukkan Bilangan:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Hasil Bilangan Desimal:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 210, 200, 30);
        getContentPane().add(MasukkanBil);
        MasukkanBil.setBounds(40, 110, 380, 30);

        BtnBiner.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnBiner.setText("Convert Biner");
        BtnBiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBinerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBiner);
        BtnBiner.setBounds(40, 160, 130, 30);

        BtnDesimal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnDesimal.setText("Convert Desimal");
        getContentPane().add(BtnDesimal);
        BtnDesimal.setBounds(270, 160, 140, 30);
        getContentPane().add(HasilBiner);
        HasilBiner.setBounds(40, 320, 370, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hasil Bilangan Biner:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 290, 160, 30);
        getContentPane().add(HasilDesimal);
        HasilDesimal.setBounds(40, 250, 370, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBinerActionPerformed
        // TODO add your handling code here:
        int bilangan = Integer.parseInt(MasukkanBil.getText().toString());
        int hasilbiner = 8;
    }//GEN-LAST:event_BtnBinerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBiner;
    private javax.swing.JButton BtnDesimal;
    private javax.swing.JTextField HasilBiner;
    private javax.swing.JTextField HasilDesimal;
    private javax.swing.JTextField MasukkanBil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
