/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul6gui;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LebarBalok = new javax.swing.JTextField();
        TinggiBalok = new javax.swing.JTextField();
        PanjangBalok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SisiKubus = new javax.swing.JTextField();
        buttonKubus = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JarijariBola = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonBola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Masukkan Lebar    :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 90, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Masukkan Tinggi   :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 140, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Masukkan Panjang:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 40, 140, 40);
        jPanel1.add(LebarBalok);
        LebarBalok.setBounds(180, 90, 100, 40);
        jPanel1.add(TinggiBalok);
        TinggiBalok.setBounds(180, 140, 100, 40);
        jPanel1.add(PanjangBalok);
        PanjangBalok.setBounds(180, 40, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 110, 34, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 160, 40, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 60, 30, 14);

        buttonBalok.setText("Hitung");
        buttonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBalokActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBalok);
        buttonBalok.setBounds(130, 210, 90, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 40, 170, 40);
        jPanel2.add(SisiKubus);
        SisiKubus.setBounds(50, 80, 110, 50);

        buttonKubus.setText("Hitung");
        buttonKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKubusActionPerformed(evt);
            }
        });
        jPanel2.add(buttonKubus);
        buttonKubus.setBounds(70, 150, 80, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 100, 18, 14);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 30, 220, 40);
        jPanel3.add(JarijariBola);
        JarijariBola.setBounds(30, 70, 120, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 90, 18, 14);

        buttonBola.setText("Hitung");
        buttonBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBolaActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBola);
        buttonBola.setBounds(50, 130, 80, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 40, 450, 310);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PROGRAM PENCARIAN VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 390, 17);

        getAccessibleContext().setAccessibleParent(this);

        setBounds(0, 0, 461, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBalokActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(PanjangBalok.getText());
        lebar = Integer.parseInt(LebarBalok.getText());
        tinggi = Integer.parseInt(TinggiBalok.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume balok adalah: " +hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_buttonBalokActionPerformed

    private void buttonKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(SisiKubus.getText());
        int hasil = sisi*sisi*sisi;
        try{
            JOptionPane.showMessageDialog(null, "Volume kubus adalah: " +hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e, "Gagal",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonKubusActionPerformed

    private void buttonBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(JarijariBola.getText());
        float hasil = (float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null, "Volume bola adalah: " +hasil, "luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error:"+e, "Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JarijariBola;
    private javax.swing.JTextField LebarBalok;
    private javax.swing.JTextField PanjangBalok;
    private javax.swing.JTextField SisiKubus;
    private javax.swing.JTextField TinggiBalok;
    private javax.swing.JButton buttonBalok;
    private javax.swing.JButton buttonBola;
    private javax.swing.JButton buttonKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
